### ISSUE TITLE
TFT35_SPI "ghost" input with KlipperScreen

### ISSUE THREAD

**Issue by staticanime** [bigtreetech/TFT35-SPI#11]
At random intervals, the KlipperScreen display on the TF35_SPI will change menus, as if someone has pressed a menu button, without anyone having physically interacted with the screen. 

I observed this while trying to diagnose why my heaters were self-activating, until I observed the KlipperScreen display change to the Temperature menu and activate the PLA option without me physically touching the screen. I've since observed it also entering the Extrude menu as well without physical touch. 

This is quite concerning, as it's caused the printer to heat up to 195/40 several times without my knowledge, and could have led to a nasty accident. Has anyone come across anything like this before? My thoughts are potentially some sort of interference with the SPI ribbon cable, is it especially sensitive to EMI, etc?

Current set up is a Voron 2.4 (Micron+) running a Manta M8P v1.1 with a CB1, U2C, EBB36 and the TFT35_SPI

**Comment by bthubs** [comment]
I've had this happen to me before. I found the mount I was using was too tight and somehow registers an input. Try loosening yours, check if your ribbon cable is seated properly and intact.  If not that, try upgrading to the latest release, there appears to be some bug fixes related to the touch input.

**Comment by staticanime** [comment]
Ok, have loosened the mount a little and will keep a tight eye on it and report back after the weekend if there are any further issues or not. Also have a shorter ribbon cable on the way, the stock one is about 60% too long for where I have it, so swapping that might help too

**Comment by bthubs** [comment]
> try upgrading to the latest release

Clarifying - for the CB1, the optimization of the touch interface was in V2.3.2.

**Comment by staticanime** [comment]
> > try upgrading to the latest release
> 
> Clarifying - for the CB1, the optimization of the touch interface was in V2.3.2.

Already on 2.3.3

**Comment by bthubs** [comment]
> > > try upgrading to the latest release
> > 
> > 
> > Clarifying - for the CB1, the optimization of the touch interface was in V2.3.2.
> 
> Already on 2.3.3

You know what, it’s probably not the tightness of the mount as this is a capacitive screen, that shouldn’t register an input. I own several of these and had a few have that issue, and replacing it solved the issue, suggesting it’s probably not the ribbon. You probably have a bad screen. Try recalibrating the touch, there’s a guide in this repository. Or replace it if that doesn’t work.

**Comment by staticanime** [comment]
Can confirm, loosening off the mount has solved the issue!!
