### ISSUE TITLE
Wrong/bad Touch registraction.

### ISSUE THREAD

**Issue by za-x-az** [bigtreetech/TFT35-SPI#6]
How to re-calibrate touch?
I almost can't click left side buttons screen things I'm touching 5-10mm further right than I am.

**Comment by Escrich** [comment]
Same for me, I'm trying to calibrate my tft35 spi screen, through the help of BTT official page in Facebook, by the moment I'm able to start the calibrate process, carefully calibrating it, pointing in the calibration points, using the tip of my electronic pencil for screens, and record the calibrating output, but looks like if the system will not use at all, the recorded calibrating values, left buttons are unusable, even using an electronic pencil for screens, and everityme you need to use them, you start, not wanting to do it, the homing process at the printer, I'm almost the whole day homing and homing my printer


![BTT CB1 and TF35 Screen with e-pencil](https://github.com/bigtreetech/TFT35-SPI/assets/45154631/be6f62b1-6c12-4463-90c3-db809c5bc887)
![BTT CB1 and TF35 Screen](https://github.com/bigtreetech/TFT35-SPI/assets/45154631/0bfcb061-f364-4746-b6c3-e6e482eba458)

**Comment by taragor** [comment]
How did you start the calibration process? Facing the same issue but cant find any ressources how to calibrate this display

**Comment by Escrich** [comment]
Info received in the offficial BTT channel in Facebook
BY Patrick Myrseth
Screen calibration on BTT TFT35 SPI

log in with ssh
sudo apt-get update
sudo apt-get install libts-dev -y
sudo nano /etc/ts.conf
uncomment module median depth=5
ctrl-x to exit, y to write, enter to save, or as I do ctrl-o to save, Enter to confirm, and ctrl-x to exit
export TSLIB_TSDEVICE=/dev/input/event0
export TSLIB_FBDEVICE=/dev/fb1
sudo ln -s /dev/input/event0 /dev/input/ts
sudo ts_calibrate
Follow the screen prompts
sudo reboot after done.


Once done, if you need to re-calibrate, my suggestion is to create once a new file in your home directory, like my calib.sh, and run it every time you need to try to calibrate, you'll start the process with this simple command sudo ./calib.sh, instead to rewrite the most of the code.
Inside my file I have this contents:

#!/bin/bash

export TSLIB_TSDEVICE=/dev/input/event0
export TSLIB_FBDEVICE=/dev/fb1
sudo ln -s /dev/input/event0 /dev/input/ts
sudo ts_calibrate

**Comment by Escrich** [comment]
Please, let me know if once calibrated you could see any behaviour difference, thanks

**Comment by tommymonk** [comment]
I'm experiencing the same issue, can't really press any button on the far left, I ran through the calibration step above and it seems no different after reboot, so you have to somehow save the data it outputs after the calibrate in order to apply it ?

**Comment by Escrich** [comment]
Data really it's saved in /etc/pointercal

**Comment by tommymonk** [comment]
@Escrich so is the calibration also not having an effect for you ?

**Comment by Escrich** [comment]
Exactly, this is the issue, I make the complete calibration process, but once done looks like having not effect at all over touchscreen behaviour

**Comment by tommymonk** [comment]
Lets hope that your Facebook conversion with them helps us.

**Comment by Escrich** [comment]
Looks like in a dead endJose M. EscrichEl 25 may 2023 18:45, tommymonk ***@***.***> escribió:
Lets hope that your Facebook conversion with them helps us.

**Comment by Escrich** [comment]
Looks like in a dead end

**Comment by Escrich** [comment]
Few minutes ago I wrote them again

**Comment by tommymonk** [comment]
@bigtreetech can we have some official word on this please

**Comment by Kiiiddd** [comment]
Yeah I have the Same issue with the left side of the screen barely working. I am using a Manta M8P with CB1

**Comment by Escrich** [comment]
@bigtreetech We need an official answer, right now!

**Comment by Krisstank** [comment]
> Info received in the offficial BTT channel in Facebook BY Patrick Myrseth Screen calibration on BTT TFT35 SPI
> 
> log in with ssh sudo apt-get update sudo apt-get install libts-dev -y sudo nano /etc/ts.conf uncomment module median depth=5 ctrl-x to exit, y to write, enter to save, or as I do ctrl-o to save, Enter to confirm, and ctrl-x to exit export TSLIB_TSDEVICE=/dev/input/event0 export TSLIB_FBDEVICE=/dev/fb1 sudo ln -s /dev/input/event0 /dev/input/ts sudo ts_calibrate Follow the screen prompts sudo reboot after done.
> 
> Once done, if you need to re-calibrate, my suggestion is to create once a new file in your home directory, like my calib.sh, and run it every time you need to try to calibrate, you'll start the process with this simple command sudo ./calib.sh, instead to rewrite the most of the code. Inside my file I have this contents:
> 
> #!/bin/bash
> 
> export TSLIB_TSDEVICE=/dev/input/event0 export TSLIB_FBDEVICE=/dev/fb1 sudo ln -s /dev/input/event0 /dev/input/ts sudo ts_calibrate

after doing this method i can no longer use a web browser to view my klipper menus any suggestion to revert this back? i just get a 403 error message

**Comment by Escrich** [comment]
Look for the new IP you have nowJose M. EscrichEl 12 jun 2023 7:28, Kris Stankievech ***@***.***> escribió:

Info received in the offficial BTT channel in Facebook BY Patrick Myrseth Screen calibration on BTT TFT35 SPI
log in with ssh sudo apt-get update sudo apt-get install libts-dev -y sudo nano /etc/ts.conf uncomment module median depth=5 ctrl-x to exit, y to write, enter to save, or as I do ctrl-o to save, Enter to confirm, and ctrl-x to exit export TSLIB_TSDEVICE=/dev/input/event0 export TSLIB_FBDEVICE=/dev/fb1 sudo ln -s /dev/input/event0 /dev/input/ts sudo ts_calibrate Follow the screen prompts sudo reboot after done.
Once done, if you need to re-calibrate, my suggestion is to create once a new file in your home directory, like my calib.sh, and run it every time you need to try to calibrate, you'll start the process with this simple command sudo ./calib.sh, instead to rewrite the most of the code. Inside my file I have this contents:
#!/bin/bash
export TSLIB_TSDEVICE=/dev/input/event0 export TSLIB_FBDEVICE=/dev/fb1 sudo ln -s /dev/input/event0 /dev/input/ts sudo ts_calibrate

after doing this method i can no longer use a web browser to view my klipper menus any suggestion to revert this back?

**Comment by Krisstank** [comment]
nothing has changed IP wise i can still SSH into the Pi and send files VIA its IP i just can no longer view my machine VIA a webpage

**Comment by Escrich** [comment]
Those method can't do the changes you are suffering

**Comment by Krisstank** [comment]
Odly enough it was from running the update on wifi that errored out, putting it on ethernet and redoing it corrected the issue

**Comment by thiagomagamoc** [comment]
Has anyone found a solution? For me, even after calibrating the display, there is no effect, like the other comments above

**Comment by tommymonk** [comment]
Nope, @bigtreetech have also completely ignored my support request.

**Comment by za-x-az** [comment]
Im in a long and borring email chain. this is the last I received,

`Hi, thank you for your information.

We have reported your situation to our engineers before, and they are still working on a software for calibrating, it might take a few days.

Sorry for the waiting.

`

**Comment by Escrich** [comment]
I hope this time we'll get the right answer, including , of course, the solution

**Comment by Escrich** [comment]
> 

Still waiting for a solution in how to calibrate the screen in a valid way, do you thing the "promised few days" has been yet expired?

**Comment by Escrich** [comment]
any news?

**Comment by taragor** [comment]
I've just stumbled over this guide and it seems to have solved the issue for me.
https://bigtreetech.github.io/docs/libinput_calibration.html

edit: after some further testing following the linked steps completly solves the calibration issues for me, and the calibration is persistant between reboots. 
While it is not the most Streamlined or userfriendly process I think the linked doc should be mentioned in the readme of this repo

**Comment by Tollie46** [comment]
@taragor thank you man this solved the problem for me and everything responds normally now

**Comment by Escrich** [comment]
Finally working, thanks

**Comment by JanB97** [comment]
> I've just stumbled over this guide and it seems to have solved the issue for me. https://bigtreetech.github.io/docs/libinput_calibration.html
> 
> edit: after some further testing following the linked steps completly solves the calibration issues for me, and the calibration is persistant between reboots. While it is not the most Streamlined or userfriendly process I think the linked doc should be mentioned in the readme of this repo

I tried this and now my touch is completely off, do you now how to revert this?

**Comment by pauluchin** [comment]
Works 4 me 

Thanks
